name: Scrape latest help

on:
  workflow_dispatch:
  schedule:
    - cron:  '35 4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure Python with pip cache
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: '**/.github/workflows/*.yml'
    - name: Configure Git for commits
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
    - name: Scrape gcloud
      run: |-
        sh gcloud.sh
    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "gcloud: ${timestamp}" || exit 0
        git push
